import Foundation

enum Config {
    static let maxConstant = 1024
    static let maxUnsignedBinary = 32
    static let maxSignedBinary = 16
    static let maxShift = 8
    static let maxPowExponent = 10
}

func unsignedExpr(_ value: Int) -> String {
    precondition(value >= 0)
    if value == 0 {
        return "UTerm"
    }
    if value == 1 {
        return "UOne"
    }

    let binary = String(value, radix: 2)
    // The leading bit is always 1, represented by UOne.
    var expr = "UOne"
    for bit in binary.dropFirst() {
        expr = "UInt<\(expr), \(bit == "1" ? "B1" : "B0")>"
    }
    return expr
}

func signedTypeName(_ value: Int) -> String {
    if value == 0 { return "Z0" }
    if value > 0 { return "P\(value)" }
    return "N\(-value)"
}

func unsignedTypeName(_ value: Int) -> String {
    "U\(value)"
}

func integerTypeName(_ value: Int, unsigned: Bool = false) -> String {
    unsigned ? unsignedTypeName(value) : signedTypeName(value)
}

func maskedNot(_ value: Int) -> Int {
    guard value > 0 else { return 0 }
    let width = Int.bitWidth - value.leadingZeroBitCount
    let mask = (1 << width) - 1
    return value ^ mask
}

func checkedPow(_ base: Int, _ exponent: Int) -> Int? {
    var result = 1
    for _ in 0..<exponent {
        let next = result.multipliedReportingOverflow(by: base)
        if next.overflow {
            return nil
        }
        result = next.partialValue
    }
    return result
}

func emitConstants() -> String {
    var lines: [String] = [
        "// Generated by TypenumCodegen. Do not edit manually.",
        "",
        "// MARK: - Unsigned constants",
    ]

    for n in 0...Config.maxConstant {
        lines.append("public typealias U\(n) = \(unsignedExpr(n))")
    }

    lines.append("")
    lines.append("// MARK: - Signed constants")

    for n in 1...Config.maxConstant {
        lines.append("public typealias P\(n) = PInt<U\(n)>")
        lines.append("public typealias N\(n) = NInt<U\(n)>")
    }

    return lines.joined(separator: "\n")
}

func emitUnaryProofs() -> String {
    // TODO: Generate marker conformances (e.g. PowerOfTwo) once Swift supports
    // non-overlapping conditional conformances for specific generic instantiations.
    let lines: [String] = ["", "// MARK: - Unary proofs"]

    return lines.joined(separator: "\n")
}

func emitUnsignedBinaryProofs() -> String {
    // TODO: Generate binary operation proofs when proof-driven constraints
    // are extended beyond the current Pow2Proof pattern (see ADR-0003).
    [
        "",
        "// MARK: - Unsigned binary proofs",
    ]
    .joined(separator: "\n")
}

func emitSignedBinaryProofs() -> String {
    // TODO: Generate signed binary operation proofs when proof-driven constraints
    // are extended beyond the current Pow2Proof pattern (see ADR-0003).
    [
        "",
        "// MARK: - Signed binary proofs",
    ]
    .joined(separator: "\n")
}

func gcd(_ a: Int, _ b: Int) -> Int {
    var x = a
    var y = b
    while y != 0 {
        (x, y) = (y, x % y)
    }
    return abs(x)
}

let outputPath = CommandLine.arguments[1]
let text = [
    emitConstants(),
    emitUnaryProofs(),
    emitUnsignedBinaryProofs(),
    emitSignedBinaryProofs(),
]
.joined(separator: "\n")

try text.write(toFile: outputPath, atomically: true, encoding: .utf8)
